require([
    'avoid_console_conflicts',
    'general_functions',
    'menu',
    'colors',
    'tables',
    'accordion_setup',
    'clickable',
    'search',
    'toggle',
    'breadcrumbs',
    'header',
    'footer',
    'polyfills',
    'select_dropdown',
    'faq',
    'magnific_init'
    /*,'analytics'*/
]);